config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'error_top', to: "static_pages#error_top"

  # メール機能 ============================================================================
  get '/request_mail/preview', to: 'request_mails#preview_mail'
  post '/request_mail/create', to: 'request_mails#send_mail'

  # 新規ユーザ作成（施設・ご家族） ========================================================
  resources :signup do
    collection do
      get 'step1'
      get 'step2' # ここで、入力が終了
      get 'step3'
      get 'search'
    end
  end

  # devise（施設・ご家族） ================================================================
  devise_for :facilities, controllers: {
      sessions: 'facilities/sessions',
      passwords: 'facilities/passwords',
      registrations: 'facilities/registrations'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :facility do
    get 'facility_sign_in', to: "facilities/sessions#new"
    get 'facility_sign_out', to: "facilities/sessions#destroy"
  end

  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
    get 'sign_out', to: "users/sessions#destroy"
    get 'privacy', to: "users/sessions#privacy"
  end

  # 施設 ==================================================================================
  resources :facilities do
    get :home # ユーザログイン後の各施設のホーム画面
    get :facility_home, on: :member # 施設ログイン後のホーム画面
    resources :reservations do # 予約機能
      collection do
        get :index_week
        get :index_past
      end
      get '/reservation_time/:date', on: :collection, to: 'reservations#reservation_time', as: :reservation_time
    end
    # get 'inquiry', to: "facilities/inquiries#inquiry"
    # post 'create', to: "facilities/inquiries#create"
    resources :inquiries do
      get :inquiry, on: :collection
    end
  end

  # ご家族 ================================================================================
  resources :users do
    member do
      get :video_room
    end
    resources :rooms, only: %i[new create edit update]
    resources :affiliations, only: %i[create destroy]
  end

  # カレンダー設定 =========================================================================
  resources :calendar_settings, except: :index

  # 利用施設登録 ==========================================================================
  resources :facility_users, only: %i[new update destroy] do
    member do
      patch :facility_update
    end
  end

  # 入居者 ================================================================================
  resources :residents do
    patch :leave_update, on: :member # 入退所
    resources :memories do # 思い出アルバム
      delete '/delete_image/:memory_id/:column', on: :collection, to: 'memories#delete_image', as: :delete_image
    end
  end

  # 入居者申請 ============================================================================
  resources :request_residents

  # 入居者登録 ============================================================================
  resources :relatives, except: %i[create] do
    get :confirm, on: :member
    patch :denial, on: :member
    patch :update_relatives, on: :collection
  end

  # お知らせ ==============================================================================
  resources :informations

  # タグ ==================================================================================
  resources :tags
  resources :tag_images

  # お問い合わせ ==========================================================================
  resources :inquiries do
    collection do
      get :inquiry
      get :inquiry_system
      post :create_system
    end
  end

  # 例外処理 ==============================================================================
  # get '*path', to: 'application#render_404'
end

app/models/facility.rb
class Facility < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :informations, dependent: :destroy
  has_many :residents, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :calendar_setting, dependent: :destroy
  # User:Facility = 多対多 ・・・関連付け
  has_many :facility_users, dependent: :destroy
  has_many :users, through: :facility_users

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :facility_name, presence: true, length: { maximum: 20 }
  validates :email,                   presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  # モデル | ImageUploaderクラスとimageカラムを紐づける
  mount_uploader :image, ImageUploader
  mount_uploader :icon, ImageUploader

  # cookieでログイン情報を保持
  def remember_me
    true
  end

  # search定義
  def self.search(search)
    where.not(admin: true).order(:id) unless search
    where('facility_name LIKE ?', "%#{search}%").where.not(admin: true).order(:id)
  end

  def build_with_url(information_params)
    information_params[:url] = information_params[:url].last(11)
    informations.build(information_params)
  end
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :user
  belongs_to :resident

  # search定義
  def self.search(search, facility)
    return facility.residents.where('name LIKE ?', "%#{search}%").order(:id) if search.present?

    facility.residents
  end

  def self.reject_zero(resident_ids)
    resident_ids.map(&:to_i).reject(&:zero?).sort
  end

  def self.new_update_ids(update_ids)
    update_ids[:set_ids] = [] if update_ids[:set_ids].nil?
    new_resident_ids = update_ids[:resident_ids].concat(update_ids[:set_ids])
    update_ids.delete(:set_ids)
    reject_zero(new_resident_ids)
  end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  before_action :set_request, only: %i[show edit update destroy]
  before_action :set_user, only: %i[show edit]
  before_action :set_residents, except: %i[destroy index]
  before_action :set_active_requests, except: %i[new confirm destroy index]

  # 申請一覧
  def new
    if params[:update_relatives].present?
      hash = {}
      update_relatives_params.each do |id, item|
        hash[RequestResident.where(facility_id: current_facility).where(req_approval: "request").find_by(user_id: id)] = item
      end
      @requests = hash.sort.reverse.to_h
    else
      @requests = RequestResident.active(current_facility)
    end
  end

  # 確認画面
  def confirm
    @request_residents = confirm_params
  end

  # 一括で承認
  def update_relatives
    update_relatives_params.each do |id, update_ids|
      user = User.find(id)
      unless Relative.new_update_ids(update_ids) == user.resident_ids.sort
        user.update_attributes(update_ids)
        RequestResident.update_approval(current_facility, id)
      end
    end
    redirect_to facility_home_facility_url(current_facility), notice: "まとめて承認しました。"
  end

  # 個別に承認・否認
  def update
    @user = User.find(params[:user_id].to_i)
    if @user.update_with_context(update_params, context: :relative_update)
      request_resident = RequestResident.changer(current_facility, @user)
      request_resident.approval!
      flash[:notice] = "#{request_resident.user.name}の申請を承認しました。"
      request.referer.include?("edit") ? redirect_to(relatives_url) : redirect_to(facility_home_facility_url(current_facility))
    else
      request.referer.include?("edit") ? (render :edit) : (render :show)
    end
  end

  # 承認済み申請一覧
  def index
    @applied_ids = RequestResident.search(params[:search], current_facility)
  end

  def show; end

  def edit; end

  def destroy; end

  def denial
    @request = RequestResident.find(params[:id])
    @request.denial!
    RequestMailer.send_denial_to_user(current_facility, @request).deliver
    flash_message = "#{@request.user.name}の申請を否認しました。"

    respond_to do |format|
      format.html do
        flash[:notice] = flash_message
        request.referer.include?("edit") ? redirect_to(relatives_url) : redirect_to(facility_home_facility_url(current_facility))
      end
      format.js { flash.now[:notice] = flash_message }
    end
  end

  private

    def confirm_params
      params.require(:facility).permit(request_residents: [resident_ids: [], set_ids: []])[:request_residents]
    end

    def update_relatives_params
      permited_hash = {}
      params.require(:update_relatives).each_pair do |id, value|
        permited_hash[id] = value.permit(resident_ids: [], set_ids: [])
      end
      permited_hash
    end

    def update_params
      params.require(:user).permit(resident_ids: [])
    end

    def set_request
      @request = RequestResident.find(params[:id])
    end

    def set_user
      @user = User.find(@request.user_id)
    end

    def set_residents
      @residents = Relative.search(params[:search], current_facility)
    end

    def set_active_requests
      @requests = RequestResident.active(current_facility)
    end
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/relatives/_confirm.html.erb
<div class="relative-confirm-body">
  <% @request_residents.each do |user, r_ids| %>
    <% current_facility.acceptance_requests(user).each do |request| %>
    <% request = ActiveDecorator::Decorator.instance.decorate(request) %>
      <div class="request-time"><span>申請日</span><%= l(request.created_at, format: :long) %></div>
      <div class="card">
        <div class="relative-new-container">
          <div class="relative-confirm-section">
            <table class="table is-narrow user-edit-table is-bordered" id="relative-confirm-table">
              <tbody>
                <tr>
                  <th colspan="2">
                    <div class="relative-confirm-req-name">
                      <h1 class="has-text-weight-bold is-size-4"><%= request.user.name %><span class="is-size-5 req-name"> 様からの申請</span></h1>
                    </div>
                  </th>
                </tr>
                <tr>
                  <th>利用者名</th>
                  <td>
                    <%= simple_format(request.req_name) %>
                  </td>
                </tr>
                <tr>
                  <th>連絡先</th>
                  <td>
                    <%= request.user.phone %>
                  </td>
                </tr>
                <tr>
                  <th>住所</th>
                  <td>
                    <%= request.user.address %>
                  </td>
                </tr>
                <tr>
                  <th>紐付け</th>
                  <td>
                    <p class="is-size-7">（登録済み入居者）</p>
                    <% if request.user.residents.map(&:facility_id).include?(current_facility.id) %>
                      <% request.user.residents.each do |resident| %>
                        <span class="registered-name"><%= resident.name if resident.facility_id == current_facility.id %></span>
                      <% end %><br><br>
                    <% else %>
                      <p class="registered-name">現在登録されている利用者はいません</p><br>
                    <% end %>

                    <p>↓↓</p>

                    <p class="is-size-7">（承認後の入居者）</p>
                    <% if current_facility.newly_numbers(r_ids).sort == request.user.resident_ids.sort %>
                      <p class="c-red has-text-weight-bold">申請を保留します</p>
                    <% else %>
                      <% current_facility.newly_numbers(r_ids).each do |r_id| %>
                        <span class="approval-name"><%= current_facility.resident_name(r_id) %></span>
                      <% end %>
                    <% end %>

                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="confirm-submit">
    <%= link_to '入力画面に戻る', new_relative_path(update_relatives: @request_residents), method: :get, remote: true, class: "button is-light has-text-weight-bold", id: "req-submit" %>
    <%= link_to 'まとめて承認', update_relatives_relatives_path(update_relatives: @request_residents), method: :patch, remote: true, class: "button is-primary is-light has-text-weight-bold", id: "req-submit" %>
  </div>
</div>

app/views/relatives/_new.html.erb
<div class="render-content">
  <div id="flash-message"></div>
  <div class="relative-new-body">
    <% if !params[:update_relatives].present? %>
      <%= form_with(url: new_relative_path, method: :get, remote: true) do |f| %>
        <div class="field is-grouped is-grouped-right">
          <div class="control has-icons-left">
            <%= f.text_field :search, :placeholder => "利用者名を入力..", class: "input is-rounded" %>
            <span class="icon is-left">
              <i class="fas fa-search" aria-hidden="true"></i>
            </span>
          </div>
          <div class="control">
            <%= f.submit "\uf002検索", class: "fa button is-link is-outlined is-rounded" %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= form_with(model: current_facility, url: confirm_relative_path(current_facility), method: :get, remote: true) do |f| %>
      <% @requests.each do |request, selected_ids| %>
        <% request = ActiveDecorator::Decorator.instance.decorate(request) %>
        <% if request.req_approval == "request" %>
          <div class="request-time" id="time-<%= request.id %>"><span>申請日</span><%= l(request.created_at, format: :long) %></div>
          <div class="card" id="card-<%= request.id %>">
            <div class="relative-new-container">
              <div class="relative-new-section">
                <table class="table is-narrow user-edit-table is-bordered" id="relative-table">
                  <tbody>
                    <tr>
                      <th colspan="2">
                        <div class="relative-new-req-name">
                          <h1 class="has-text-weight-bold is-size-4"><%= request.user.name %><span class="is-size-5 req-name"> 様からの申請</span></h1>
                            <div>
                              <%= link_to request_mail_preview_path(denial: request), class: "button", id: "preview-#{request.id}", method: :get, remote: true do %>
                                <i class="far fa-envelope"></i><span>メール</span>
                              <% end %>
                            </div>

                            <div class="new-cancel-btn">
                              <%= link_to denial_relative_path(request), class:"button is-rounded new-denial-btn", id: "denial-mail-submit-#{request.id}", method: :patch, remote: true do %>
                                <div class="relative_cp_tooltip"><i class="fas fa-times"></i>否認する<span class= "relative_cp_tooltiptext">※否認と同時にメール送信されます</span></div>
                              <% end %>
                            </div>
                        </div>
                      </th>
                    </tr>
                    <tr>
                      <th>利用者名</th>
                      <td>
                        <%= simple_format(request.req_name) %>
                      </td>
                    </tr>
                    <tr>
                      <th>連絡先</th>
                      <td>
                        <%= request.user.phone %>
                      </td>
                    </tr>
                    <tr>
                      <th>住所</th>
                      <td>
                        <%= request.user.address %>
                      </td>
                    </tr>
                    <tr>
                      <th>紐付け</th>
                      <td>
                        <%= render partial: 'shared/error_messages', locals: { obj: @request_user } if @request_user.present? %>
                        <%= f.fields_for "request_residents[]", request.user do |i| %>

                          <% if selected_ids.present? %>
                            <% request.user.send_ids(selected_ids) %>
                            <div class="new-checkbox">
                              <%= i.collection_check_boxes :set_ids, @residents, :id, :name do |b| %>
                                <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                              <% end %><br>
                            </div>
                          <% else %>
                            <div class="new-checkbox">
                              <%= i.collection_check_boxes :resident_ids, @residents, :id, :name do |b| %>
                                <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                              <% end %><br>
                            </div>
                          <% end %>

                          <div class="d-none">
                            <%= i.collection_check_boxes :resident_ids, request.exclude_ids, :id, :name do |b| %>
                              <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                            <% end %>
                          </div>
                          <div class="tag-apply">
                            <%= i.collection_check_boxes :resident_ids, request.user.residents, :id, :name, class: 'd-none' do |b| %>
                              <% if b.object.facility_id == current_facility.id  %>
                                <span class="tag is-warning r-tag"><%= b.label { b.text } %>承認済</span>
                              <% end %>
                            <% end %>
                          </div>

                        <% end %>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <%= f.submit "確認画面へ", class: "button is-link is-light has-text-weight-bold", id: "req-submit" if @requests.present? %>
    <% end %>
  </div>
</div>

<!-- モーダル表示 -->
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card" id="mail-modal-card">
    <div class="modal-mail-form"></div>
  </div>
</div>

app/views/relatives/confirm.html.erb
<div class="relative-confirm-body">
  <% @request_residents.each do |user, r_ids| %>
    <% current_facility.acceptance_requests(user).each do |request| %>
    <% request = ActiveDecorator::Decorator.instance.decorate(request) %>
      <div class="request-time"><span>申請日</span><%= l(request.created_at, format: :long) %></div>
      <div class="card">
        <div class="relative-new-container">
          <div class="relative-confirm-section">
            <table class="table is-narrow user-edit-table is-bordered" id="relative-confirm-table">
              <tbody>
                <tr>
                  <th colspan="2">
                    <div class="relative-confirm-req-name">
                      <h1 class="has-text-weight-bold is-size-4"><%= request.user.name %><span class="is-size-5 req-name"> 様からの申請</span></h1>
                    </div>
                  </th>
                </tr>
                <tr>
                  <th>利用者名</th>
                  <td>
                    <%= simple_format(request.req_name) %>
                  </td>
                </tr>
                <tr>
                  <th>連絡先</th>
                  <td>
                    <%= request.user.phone %>
                  </td>
                </tr>
                <tr>
                  <th>住所</th>
                  <td>
                    <%= request.user.address %>
                  </td>
                </tr>
                <tr>
                  <th>紐付け</th>
                  <td>
                    <p class="is-size-7">（登録済み入居者）</p>
                    <% if request.user.residents.map(&:facility_id).include?(current_facility.id) %>
                      <% request.user.residents.each do |resident| %>
                        <span class="registered-name"><%= resident.name if resident.facility_id == current_facility.id %></span>
                      <% end %><br><br>
                    <% else %>
                      <p class="registered-name">現在登録されている利用者はいません</p><br>
                    <% end %>

                    <p>↓↓</p>

                    <p class="is-size-7">（承認後の入居者）</p>
                    <% if current_facility.newly_numbers(r_ids).sort == request.user.resident_ids.sort %>
                      <p class="c-red has-text-weight-bold">申請を保留します</p>
                    <% else %>
                      <% current_facility.newly_numbers(r_ids).each do |r_id| %>
                        <span class="approval-name"><%= current_facility.resident_name(r_id) %></span>
                      <% end %>
                    <% end %>

                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="confirm-submit">
    <%= button_to "入力画面に戻る", new_relative_path, params: {update_relatives: @request_residents}, class: "button is-light has-text-weight-bold", id: "req-submit" %>
    <%= link_to 'まとめて承認', update_relatives_relatives_path(update_relatives: @request_residents), method: :patch, class: "button is-primary is-light has-text-weight-bold", id: "req-submit" %>
  </div>
</div>

app/views/relatives/confirm.js.erb
document.querySelector(".render-content").innerHTML = "<%= escape_javascript(render 'confirm') %>";

app/views/relatives/denial.js.erb
$("#time-<%= @request.id %>").remove();

$("#card-<%= @request.id %>").remove();

$("#flash-message").html("<div class='notification is-success has-text-weight-bold'><p class='notice'><%= notice %></p></div>").hide().fadeIn(100);

$(function(){
  setTimeout("$('#flash-message').fadeOut(1200)", 12000)
})

$(".loading-panel-wrap").remove();

app/views/relatives/edit.html.erb
<div class="relative-show-body">
  <div id="flash-message"></div>
  <div class="relative-container">
    <div class="relative-section">
      <nav class="relative-level">
        <div class="new-c-container">
          <%= form_with(url: edit_relative_path(@request), method: :get, local: true) do |f| %>
            <div class="field is-grouped is-grouped-right">
              <div class="control has-icons-left">
                <%= f.text_field :search, :placeholder => "利用者名を入力..", class: "input is-rounded" %>
                <span class="icon is-left">
                  <i class="fas fa-search" aria-hidden="true"></i>
                </span>
              </div>
              <div class="control">
                <%= f.submit "\uf002検索", class: "fa button is-light is-rounded" %>
              </div>
            </div>
          <% end %>
        </div>
      </nav>

      <div class="request-time"><span>申請日</span><%= l(@request.created_at, format: :long) %></div>
      <div class="card">
        <table class="table is-narrow user-edit-table is-bordered mb-30" id="relative-table">
          <tbody>
            <tr>
              <th colspan="2">
                <div class="relative-edit-req-name">
                  <h1 class="has-text-weight-bold is-size-4"><%= @user.name %> 様の申請は<span><%= @request.status %></span>です</h1>
                    <div>
                      <%= link_to request_mail_preview_path(denial: @request), class: "button", id: "preview-#{@request.id}", method: :get, remote: true do %>
                        <i class="far fa-envelope"></i><span>メール</span>
                      <% end %>
                    </div>
                </div>
              </th>
            </tr>
            <tr>
              <th>利用者名</th>
              <td>
                <%= simple_format(@request.req_name) %>
              </td>
            </tr>
            <tr>
              <th>連絡先</th>
              <td>
                <%= @request.user.phone %>
              </td>
            </tr>
            <tr>
              <th>住所</th>
              <td>
                <%= @request.user.address %>
              </td>
            </tr>
            <tr>
              <th>紐付け</th>
              <td>
                <%= render partial: 'shared/error_messages', locals: { obj: @user } if @user.present? %>
                <%= form_with(model: @user, url: relative_path(user_id: @user), local: true) do |f| %>
                  <div class="relative-check-box">
                    <%= f.collection_check_boxes :resident_ids, @residents, :id, :name do |b| %>
                      <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                    <% end %><br>
                  </div>
                  <div class="d-none">
                    <%= f.collection_check_boxes :resident_ids, @request.exclude_ids, :id, :name do |b| %>
                      <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                    <% end %>
                  </div>

                  <div class="tag-apply">
                    <%= f.collection_check_boxes :resident_ids, @user.residents, :id, :name, class: 'd-none' do |b| %>
                      <% if b.object.facility_id == current_facility.id  %>
                        <span class="tag is-warning r-tag"><%= b.label { b.text } %>承認済</span>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="propriety">
                    <%= f.submit "承認済に変更", class: "button is-primary is-light is-midium", id: "edit-approval-btn" %>
                    <%= link_to denial_relative_path(denial: @request), method: :patch,
                      data: { confirm: "#{@user.name}の申請を否認してよろしいですか？" }, class: "button is-danger is-light is-medium", id: "edit-denial-btn" do %>
                      否認済に変更
                    <% end %>
                  </div>
                  <p class="c-red">※申請の承認/否認を変更する場合はこちらから変更が可能です</p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- モーダル表示 -->
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card" id="mail-modal-card">
    <div class="modal-mail-form"></div>
  </div>
</div>

<script>
// dispLoadingを定義
function dispLoading(msg) {
  if( msg == undefined ){
    msg = "";
  }
  // var dispMsg = "<div class='loadingMsg'>" + msg + "</div>";
  if($(".loading-panel-wrap").length == 0){
    $("body").append("<div class='loading-panel-wrap'><div class='loading-panel'><span><h3>Loading</h3></span></div><div class='shadow'></div></div>");
  }
}

$(function () {
  $("#preview-<%= @request.id %>").click( function() {
    dispLoading("");
  });
});
</script>

app/views/relatives/show.html.erb
<% if @request.req_approval == "request" %>
  <div id="flash-message"></div>
  <div class="relative-show-body">
    <div class="relative-container">
      <div class="relative-section">
        <nav class="relative-level">
          <div class="new-c-container">
            <%= form_with(url: relative_path(@request), method: :get, local: true) do |f| %>
              <div class="field is-grouped is-grouped-right">
                <div class="control has-icons-left">
                  <%= f.text_field :search, :placeholder => "利用者名を入力..", class: "input is-rounded" %>
                  <span class="icon is-left">
                    <i class="fas fa-search" aria-hidden="true"></i>
                  </span>
                </div>
                <div class="control">
                  <%= f.submit "\uf002検索", class: "fa button is-light is-rounded" %>
                </div>
              </div>
            <% end %>
          </div>
        </nav>

        <div class="request-time"><span>申請日</span><%= l(@request.created_at, format: :long) %></div>
        <div class="card">
          <table class="table is-narrow user-edit-table is-bordered" id="relative-table">
            <tbody>
              <tr>
                <th colspan="2">
                  <div class="relative-show-req-name">
                    <h1 class="has-text-weight-bold is-size-4"><%= @user.name %><span class="is-size-5 req-name"> 様からの申請</span></h1>
                      <div>
                        <%= link_to request_mail_preview_path(denial: @request), class:"button", id: "preview-#{@request.id}", method: :get, remote: true do %>
                          <i class="far fa-envelope"></i><span>メール</span>
                        <% end %>
                      </div>
                  </div>
                </th>
              </tr>
              <tr>
                <th>利用者名</th>
                <td>
                  <%= simple_format(@request.req_name) %>
                </td>
              </tr>
              <tr>
                <th>連絡先</th>
                <td>
                  <%= @request.user.phone %>
                </td>
              </tr>
              <tr>
                <th>住所</th>
                <td>
                  <%= @request.user.address %>
                </td>
              </tr>
              <tr>
                <th>紐付け</th>
                <td>
                  <%= render partial: 'shared/error_messages', locals: { obj: @user } if @user.present? %>
                  <%= form_with(model: @user, url: relative_path(user_id: @user), local: true) do |f| %>
                  <div class="relative-check-box">
                    <%= f.collection_check_boxes :resident_ids, @residents, :id, :name do |b| %>
                      <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                    <% end %><br>
                  </div>
                  <div class="d-none">
                    <%= f.collection_check_boxes :resident_ids, @request.exclude_ids, :id, :name do |b| %>
                      <span class="r-check-box"><%= b.label { b.check_box + " " + b.text } %></span>
                    <% end %>
                  </div>

                  <div class="tag-apply">
                    <%= f.collection_check_boxes :resident_ids, @user.residents, :id, :name, class: "d-none" do |b| %>
                      <% if b.object.facility_id == current_facility.id  %>
                        <span class="tag is-warning r-tag"><%= b.label { b.text } %>承認済</span>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="propriety">
                    <%= f.submit "承認", class: "button is-primary is-light is-midium has-text-weight-bold", id: "approval-btn" %>
                    <%= link_to denial_relative_path(denial: @request), method: :patch,
                      data: { confirm: "#{@user.name}の申請を否認してよろしいですか？" }, class: "button is-danger is-light is-medium", id: "denial-btn" do %>
                      否認
                    <% end %>
                  </div>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- モーダル表示 -->
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card" id="mail-modal-card">
    <div class="modal-mail-form"></div>
  </div>
</div>

<script>
// dispLoadingを定義
function dispLoading(msg) {
  if( msg == undefined ){
    msg = "";
  }
  // var dispMsg = "<div class='loadingMsg'>" + msg + "</div>";
  if($(".loading-panel-wrap").length == 0){
    $("body").append("<div class='loading-panel-wrap'><div class='loading-panel'><span><h3>Loading</h3></span></div><div class='shadow'></div></div>");
  }
}

$(function () {
  $("#preview-<%= @request.id %>").click( function() {
    dispLoading("");
  });
});
</script>