config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'error_top', to: "static_pages#error_top"

  # メール機能 ============================================================================
  get '/request_mail/preview', to: 'request_mails#preview_mail'
  post '/request_mail/create', to: 'request_mails#send_mail'

  # 新規ユーザ作成（施設・ご家族） ========================================================
  resources :signup do
    collection do
      get 'step1'
      get 'step2' # ここで、入力が終了
      get 'step3'
      get 'search'
    end
  end

  # devise（施設・ご家族） ================================================================
  devise_for :facilities, controllers: {
      sessions: 'facilities/sessions',
      passwords: 'facilities/passwords',
      registrations: 'facilities/registrations'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :facility do
    get 'facility_sign_in', to: "facilities/sessions#new"
    get 'facility_sign_out', to: "facilities/sessions#destroy"
  end

  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
    get 'sign_out', to: "users/sessions#destroy"
    get 'privacy', to: "users/sessions#privacy"
  end

  # 施設 ==================================================================================
  resources :facilities do
    get :home # ユーザログイン後の各施設のホーム画面
    get :facility_home, on: :member # 施設ログイン後のホーム画面
    resources :reservations do # 予約機能
      collection do
        get :index_week
        get :index_past
      end
      get '/reservation_time/:date', on: :collection, to: 'reservations#reservation_time', as: :reservation_time
    end
    # get 'inquiry', to: "facilities/inquiries#inquiry"
    # post 'create', to: "facilities/inquiries#create"
    resources :inquiries do
      get :inquiry, on: :collection
    end
  end

  # ご家族 ================================================================================
  resources :users do
    member do
      get :video_room
    end
    resources :rooms, only: %i[new create edit update]
    resources :affiliations, only: %i[create destroy]
  end

  # カレンダー設定 =========================================================================
  resources :calendar_settings, except: :index

  # 利用施設登録 ==========================================================================
  resources :facility_users, only: %i[new update destroy] do
    member do
      patch :facility_update
    end
  end

  # 入居者 ================================================================================
  resources :residents do
    patch :leave_update, on: :member # 入退所
    resources :memories do # 思い出アルバム
      delete '/delete_image/:memory_id/:column', on: :collection, to: 'memories#delete_image', as: :delete_image
    end
  end

  # 入居者申請 ============================================================================
  resources :request_residents

  # 入居者登録 ============================================================================
  resources :relatives, except: %i[create] do
    get :confirm, on: :member
    patch :denial, on: :member
    patch :update_relatives, on: :collection
  end

  # お知らせ ==============================================================================
  resources :informations

  # タグ ==================================================================================
  resources :tags
  resources :tag_images

  # お問い合わせ ==========================================================================
  resources :inquiries do
    collection do
      get :inquiry
      get :inquiry_system
      post :create_system
    end
  end

  # 例外処理 ==============================================================================
  # get '*path', to: 'application#render_404'
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :tag_images, dependent: :destroy

  validates :title, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # ログインしてなければ閲覧不可
  # before_action :authenticate_user!, only: %i[]
  # before_action :authenticate_facility!, only: %i[]
  # before_action :set_tag, only: %i[]

  # def index; end

  def show
    params[:tag].present? ? @all_image = params[:tag] : @tag = Tag.find(params[:id])
    @residents = current_user.residents.includes(:memories)
  end

  def new
    @tag = Tag.new
  end

  def create
    @informations = Information.where(facility_id: current_user.facilities).where(status: "others")
    @residents = current_user.residents.includes(:memories)
    @tag = current_user.tags.build(tag_params)

    respond_to do |format|
      if @tag.save
        format.html
        format.js { flash.now[:notice] = "#{@tag.title}フォルダを追加しました" }
      else
        format.js { render :new }
      end
    end
  end

  # def edit; end

  # def update; end

  def destroy
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.destroy
        format.html
        format.js { flash.now[:alert] = "#{@tag.title}フォルダを削除しました" }
        # else
        # format.js { render :new }
      end
    end
  end

  private

    def tag_params
      params.require(:tag).permit(:title)
    end

  #   def set_tag
  #     @tag = Tag.find(params[:id])
  #   end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_new.html.erb
<header class="modal-card-head" style="background-color: #48D1CC;">
  <p class="modal-card-title is-half has-text-weight-bold reserve-modal is-size-4">新しいフォルダーの作成</p>
</header>
<section class="modal-card-body">
  <!--タグの新規作成 （tags/create ⇨ create.js.erb ⇨ viewを表示）-->
  <%= form_with(model: @tag, url: tags_path, method: :post, remote: true) do |f| %>
    <div class="field">
      <div class="form-group col-sm-5">
        <%= render partial: 'shared/error_messages', locals: { obj: @tag } %>
        <%= f.text_field :title, :placeholder => "\uf303 フォルダ名を入力してください", class: "fa input" %>
      </div><br>
    </div>
    <div class="has-text-centered">
      <%= f.submit "作成する", class:"fa button is-info is-rounded is-focused has-text-weight-semibold" %>&emsp;
      <button type="button" class="button is-black is-outlined is-rounded has-text-weight-semibold js-content-form--close-button" aria-label="close" id="close">
        キャンセル
      </button>
    </div>
  <% end %>
</section>

app/views/tags/_show.html.erb
<% case @all_image
  when "all" %>
  <% @residents.each do |resident| %>
      <%= render 'memories/all_images', { image_columns: resident.image_columns, memories: resident.memories, resident: resident } %>
  <% end %>

<% when "event" %>
  <%= render 'memories/event_card', {residents: @residents } %>

<% else %>
  <% @residents.each do |resident| %>
    <% @tag.tag_images.each do |tag_image| %>
      <% resident.image_columns.each do |image| %>
        <% if Rails.env.production? %>
          <% memory_id = image.url.split("/")[6].to_i %>
          <% column = image.url.split("/")[5] %>
          <% id_column = image.url.split("/")[6] + image.url.split("/")[5] %>
          <% column_id = image.url.split("/")[5] + image.url.split("/")[6] %>
          <% url = image.url.split("/")[7] %>
          <% memory = memories.find(memory_id) %>
        <% else %>
          <% memory_id = image.url.split("/")[4].to_i %>
          <% column = image.url.split("/")[3] %>
          <% id_column = image.url.split("/")[4] + image.url.split("/")[3] %>
          <% column_id = image.url.split("/")[3] + image.url.split("/")[4] %>
          <% url = image.url.split("/")[5] %>
          <% memory = memories.find(memory_id) if facility_signed_in? %>
        <% end %>

        <% if tag_image.image == url %>
          <%= image_tag image.url, class: "img-interval index-photo-size image-id-#{tag_image.id}", id: id_column %>

            <!-- 画像モーダル表示 -->
            <div class="modal" id="<%= column_id %>">
              <div class="modal-background"></div>
              <div class="modal-card image-modal-width">
                <header class="modal-card-head" id="modal-title-back">
                  <p class="modal-card-title is-half has-text-weight-bold reserve-modal title-color">画像データ詳細</p>
                  <button class="delete" aria-label="close" id="close"></button>
                </header>

                <section class="modal-card-body image-position">
                  <%= image_tag image.url, id: "img_prev_#{column}_#{memory_id}", class: "img-interval modal-photo-size" %>
                </section>
                <section class="modal-card-body" id="content-back">
                  <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">画像名</span><%= url %></p>
                  <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">出来事の日付（行事日等）</span><%= l(image.model.event_date, format: :long) %></p>
                  <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">思い出画像タイトル</span><%= image.model.title %></p>
                  <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">ご家族へのメッセージ</span><%= image.model.message %></p>
                </section>

                <footer class="modal-card-foot footer-position res-footer">
                  <div class="tag-modal-image">
                    <!-- （tag_image/destroy ⇨ destroy.js.erb ⇨ viewを表示）-->
                    <%= link_to "\uf2ed フォルダから画像を削除", tag_image_path(tag_image),
                          data: { confirm: "フォルダから画像を削除して本当によろしいですか？" },
                          method: :delete, class: "fa button delete-btn", remote: true %>
                  </div>
                </footer>
              </div>
            </div>

            <script>
              $(document).ready(function () {
                $("#<%= id_column %>").on("click", function () {
                  $("div#<%= column_id %>").addClass("is-active");
                })
                $("#close, div.modal-background").on("click", function () {
                  $("div#<%= column_id %>").removeClass("is-active");
                })
              });
            </script>

        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tags/create.js.erb
<!--タグ新規作成ボタンを表すhtml⇨ <div class="tag-plus-btn">（user/show.html.erb）を削除-->
$("div.tag-plus-btn").remove();

<!--作成した@tag.idを持つ<li>要素を<li>の並びの一番最後の列に追加する-->
$('.user-show-tags').append("<li class='tag-link-<%= @tag.id%>' id='tag-links'><div class='tag-panel'><a class='tag-title-branch-ajax' data-remote='true' href='/tags/<%= @tag.id%>'><%= @tag.title %></a><a data-confirm='<%= @tag.title %>のフォルダを削除してよろしいですか？' class='tag-delete-btn' data-remote='true' rel='nofollow' data-method='delete' href='/tags/<%= @tag.id%>'><i class='fas fa-times'></i></a></div></li>");

<!--タグ新規作成ボタンを表すhtml⇨ <div class="tag-plus-btn"> を新たに作成された<li>要素の後ろに追加する-->
$('.user-show-tags').append("<div class='tag-plus-btn'><a class='new-folder-btn' data-remote='true' href='/tags/new'><i class='fas fa-folder-plus fa-3x'></i></a></div>");

<!--_all_images.html.erbのモーダル表示（各画像）される画面において、フォルダ選択フォームのリストに、新たに作成した@tagのデータを持つ選択リストを追加する-->
$('.select-tag').append("<option value='<%= @tag.id%>'><%= @tag.title %></option>");

<!--モーダルを閉じる-->
$("div.modal").removeClass("is-active");

<!--コントローラから受け取ったフラッシュの内容を表示する-->
$("#flash-message").html("<div class='notification is-success has-text-weight-bold'><p class='notice'><%= notice %></p></div>").hide().fadeIn(100);

<!--フラッシュを12000ms表示し、1200msの速さでfadeOut（非表示）する-->
$(function(){
  setTimeout("$('#flash-message').fadeOut(1200)", 12000)
})

app/views/tags/destroy.js.erb
<!--destroyした"@tag.id"と同じ番号を持つhtml⇨ <li class="tag-link-<%#= tag.id %>" id="tag-links"> （users/show.html.erb） を削除する-->
$(".tag-link-<%= @tag.id%>").remove();

<!--_all_images.html.erbのモーダル表示（各画像）される画面において、フォルダ選択フォームのリストで、削除した@tagのデータを持つ選択リストを削除する-->
$("select.select-tag option[value='<%= @tag.id%>']").remove();

<!--コントローラから受け取ったフラッシュの内容を表示する-->
$("#flash-message").html("<div class='notification is-danger has-text-weight-bold'><p class='alert'><%= alert %></p></div>").hide().fadeIn(100);

<!--フラッシュを12000ms表示し、1200msの速さでfadeOut（非表示）する-->
$(function(){
  setTimeout("$('#flash-message').fadeOut(1200)", 12000)
})

app/views/tags/new.html.erb
<%= form_with(model: @tag, url: tags_path, method: :post, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: { obj: @tag } %>
  <label class="media-left has-text-weight-bold">
    <h1 class="mini-title" style="font-size: 20px; color: #401c00;">新しいフォルダーの作成</h1>
  </label>
  <div>
    <%= f.text_field :title, :placeholder => "\uf303 タイトルを入力してください", class: "fa input" %>
  </div>
  <%= f.submit "作成する", class: "info-btn" %>
<% end %>

app/views/tags/new.js.erb
<!--.js-contents--content-formにtags/newをrenderして埋め込む-->
document.querySelector(".js-contents--content-form").innerHTML = "<%= escape_javascript(render 'new') %>";

<!--モーダル表示する-->
document.querySelector(".modal").classList.add("is-active");

<!--モーダルを閉じる、モーダル外を押下でモーダルを閉じる-->
$(".js-content-form--close-button, div.modal-background").on("click", function() {
  $("div.modal").removeClass("is-active");
})

app/views/tags/show.js.erb
$('#tag-images-view').html("<%= escape_javascript(render 'show') %>").hide().fadeIn();