config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'error_top', to: "static_pages#error_top"

  # メール機能 ============================================================================
  get '/request_mail/preview', to: 'request_mails#preview_mail'
  post '/request_mail/create', to: 'request_mails#send_mail'

  # 新規ユーザ作成（施設・ご家族） ========================================================
  resources :signup do
    collection do
      get 'step1'
      get 'step2' # ここで、入力が終了
      get 'step3'
      get 'search'
    end
  end

  # devise（施設・ご家族） ================================================================
  devise_for :facilities, controllers: {
      sessions: 'facilities/sessions',
      passwords: 'facilities/passwords',
      registrations: 'facilities/registrations'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :facility do
    get 'facility_sign_in', to: "facilities/sessions#new"
    get 'facility_sign_out', to: "facilities/sessions#destroy"
  end

  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
    get 'sign_out', to: "users/sessions#destroy"
    get 'privacy', to: "users/sessions#privacy"
  end

  # 施設 ==================================================================================
  resources :facilities do
    get :home # ユーザログイン後の各施設のホーム画面
    get :facility_home, on: :member # 施設ログイン後のホーム画面
    resources :reservations do # 予約機能
      collection do
        get :index_week
        get :index_past
      end
      get '/reservation_time/:date', on: :collection, to: 'reservations#reservation_time', as: :reservation_time
    end
    # get 'inquiry', to: "facilities/inquiries#inquiry"
    # post 'create', to: "facilities/inquiries#create"
    resources :inquiries do
      get :inquiry, on: :collection
    end
  end

  # ご家族 ================================================================================
  resources :users do
    member do
      get :video_room
    end
    resources :rooms, only: %i[new create edit update]
    resources :affiliations, only: %i[create destroy]
  end

  # カレンダー設定 =========================================================================
  resources :calendar_settings, except: :index

  # 利用施設登録 ==========================================================================
  resources :facility_users, only: %i[new update destroy] do
    member do
      patch :facility_update
    end
  end

  # 入居者 ================================================================================
  resources :residents do
    patch :leave_update, on: :member # 入退所
    resources :memories do # 思い出アルバム
      delete '/delete_image/:memory_id/:column', on: :collection, to: 'memories#delete_image', as: :delete_image
    end
  end

  # 入居者申請 ============================================================================
  resources :request_residents

  # 入居者登録 ============================================================================
  resources :relatives, except: %i[create] do
    get :confirm, on: :member
    patch :denial, on: :member
    patch :update_relatives, on: :collection
  end

  # お知らせ ==============================================================================
  resources :informations

  # タグ ==================================================================================
  resources :tags
  resources :tag_images

  # お問い合わせ ==========================================================================
  resources :inquiries do
    collection do
      get :inquiry
      get :inquiry_system
      post :create_system
    end
  end

  # 例外処理 ==============================================================================
  # get '*path', to: 'application#render_404'
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :facility

  validates :news, presence: true
  validates :title, presence: true

  enum status: { others: 0, admin: 1 }

  # モデル | ImageUploaderクラスとimageカラムを紐づける
  mount_uploader :image, ImageUploader

  scope :set_limit, -> { order(id: "DESC").limit(15) }
  scope :admin_list, -> { where(status: "admin").set_limit }
  scope :facility_list, ->(facility) { where(facility_id: facility).set_limit }

  # search定義
  def self.search(search, facility)
    facility.informations.where(status: "others").order(id: "DESC") unless search
    facility.informations.where(status: "others").where('title LIKE ?', "%#{search}%").order(id: "DESC")
  end

  def update_with_url(information_params)
    information_params[:url] = information_params[:url].last(11)
    update(information_params)
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  # ログインしてなければ閲覧不可
  before_action :authenticate_user!, only: :show
  before_action :authenticate_facility!, only: %i[index create new update destroy]
  before_action :set_information, only: %i[show edit update destroy]

  def index
    @admin_informations = Information.where(status: "admin").order(id: "DESC")
    @informations = Information.search(params[:search], current_facility).paginate(page: params[:page], per_page: 9)
  end

  def show; end

  def new
    @information = if params[:image_cache].present?
                     Information.new(information_params)
                   else
                     Information.new
                   end
  end

  def create
    @information = current_facility.build_with_url(information_params)
    @information.admin! if current_facility.admin?
    if @information.save
      redirect_to informations_url, notice: "タイトル【#{@information.title}】/お知らせを新規作成できました。"
    else
      render :new
    end
  end

  def edit; end

  def update
    @information.admin! if current_facility.admin?
    if @information.update_with_url(information_params)
      flash[:notice] = "タイトル【#{@information.title}】/お知らせを更新できました。"
      @information.status == "admin" ? redirect_to(facility_home_facility_url(current_facility)) : redirect_to(informations_url)
    else
      render :edit
    end
  end

  def destroy
    @information.destroy
    redirect_to informations_url, alert: "お知らせを削除しました"
  end

  private

    def information_params
      params.require(:information).permit(:news, :title, :image, :remove_image, :image_cache, :url)
    end

    def set_information
      @information = Information.find(params[:id])
    end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/_responsive_layout.html.erb
<section class="hero is-small" id="info-layout">
  <div class="hero-body">
    <div class="container">
    </div>
  </div>
</section>

app/views/informations/edit.html.erb
<%= render partial: 'shared/facility_images', locals: { facility: current_facility} %>

<div class="columns is-variable is-0 is-desktop facility-columns" style="margin-right: 0px; margin-top: -1.1rem;">
  <%= render 'shared/side_link' %>
  <div class="column is-10-desktop is-12-mobile" style="padding: 0px;">
    <nav class="panel" id="panel-style">
      <div class="notification-container" id="notification-mobile">
        <div class="content has-text-centered">
          <div class="columns is-centered">
            <div class="column is-10 top-btn-position is-centered">
              <h3 id="account-title">お知らせの編集ができます。</h3>
              <small style="float: right">最終更新 <%= l(@information.updated_at, format: :short) %></small>
              <h1 class="mini-title" style="font-size: 20px; color: #401c00;">お知らせ画像設定</h1>
              <p class="title-description">ここからお知らせに使用する背景画像の設定ができます。</p>
              <%= form_with(model: @information, url: information_path, method: :patch, local: true) do |f| %>
                <%= render partial: 'shared/error_messages', locals: { obj: @information } %>
                <div class="info-image-layout">
                  <%= @information.information_image %>
                </div>
                <div class="mobile-info-image-layout">
                  <%= @information.info_mobile_image %>
                  <div class="info-image-back">
                    <div class="info-image-camera">
                      <i class="fas fa-camera"></i>
                    </div>
                  </div>
                </div>
                <div class="drop-zone-area-info">
                  <%= f.label :image, "\uf574", class: "fa image_input_comment" %>
                  <%= f.file_field :image, value: "upload", class: "image_uploading" %>
                  <%= f.hidden_field :image_cache %>
                </div>
                <div class="delete-check">
                  <%= f.check_box :remove_image, id: "img_info_delete" %>
                  <label for="img_info_delete" class="check_position">使用中の画像を削除してデフォルト画像に戻したい場合のみチェックを入れて下さい。</label>
                </div>
                <div class="position-control"><h1>位置調整</h1></div>
                <div id="edit-info-sub" class="info-sub-title">
                  <p>お知らせタイトル</p>
                </label>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_field :title, :placeholder => "\uf303 タイトルを入力してください", class: "fa input" %>
                  </div>
                </div>
                <div class="info-sub2-title">
                  <p>本文</p>
                </div>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_area :news, :placeholder => "\uf303 お知らせを入力してください", class: "fa textarea" %>
                  </div>
                </div>
                <div class="info-sub2-title">
                  <p>YouTube動画<span>(※動画URLの末尾から11文字が表示されます)</span></p>
                </div>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_field :url, :placeholder => "\uf303 動画URLを貼り付けてください", class: "fa input" %>
                  </div>
                </div>
                <%= f.submit "お知らせを更新する", class: "info-btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= render 'responsive_layout' %> <!--レスポンシブ対応のため記述-->

  </div>
</div>

<script>
  $(function() {
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $(".image_uploading").change(function(){
        readURL(this);
    });
  });
</script>

<script>
  $(function() {
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#img_prev1').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $(".image_uploading").change(function(){
        readURL(this);
    });
  });
</script>

<script>
  $(function(){
    ScrollReveal().reveal('.facility-icon-image', { delay: 600, distance: '70%', origin: 'top', duration: 2000, viewFactor: 0.5 });
    ScrollReveal().reveal('#facility-name', { delay: 100, distance: '100%', origin: 'left', duration: 2000, viewFactor: 0.5 });
  });
</script>

app/views/informations/index.html.erb
<%= render partial: 'shared/facility_images', locals: { facility: current_facility} %>

<div class="columns is-variable is-0 is-desktop facility-columns" style="margin-right: 0px; margin-top: -1.1rem;">
  <%= render 'shared/side_link' %>
  <div class="column is-10-desktop is-12-mobile" style="padding: 0px;">
    <article class="panel is-success" id="panel-info">
      <div class="level-info">
        <nav class="level">

          <!-- Left side -->
          <div class="level-left">
            <p class="panel-tabs">
              <a class="panel-tab is-active infomation-tab" onclick="openTab(event,'Web')"><i class="fas fa-info-circle"></i>&nbsp;お知らせ</a>
              <a class="panel-tab infomation-tab" onclick="openTab(event,'Aud')"><i class="far fa-bell"></i>&nbsp;システムからのお知らせ</a>
            </p>
          </div>

          <!-- Right side -->
          <div class="level-right">
            <div class="info-menu">
              <%= form_with(url: informations_path, method: :get, local: true) do |f| %>
                <div class="field is-grouped is-grouped-right">
                  <div class="control has-icons-left">
                    <%= f.text_field :search, :placeholder => "タイトルを入力..", class: "input is-rounded" %>
                    <span class="icon is-left">
                      <i class="fas fa-search" aria-hidden="true"></i>
                    </span>
                  </div>
                  <div class="control">
                    <%= f.submit "\uf002検索", class: "fa button is-success is-outlined is-rounded" %>
                  </div>
                </div>
              <% end %>
              <%= link_to new_information_path do %>
                <button class="button is-success is-rounded new-info">
                  <span class="icon is-small"><i class="fas fa-bell">new</i></span>
                </button>
              <% end %>
            </div>
          </div>
        </nav>
      </div>

      <div id="Web" class="content-tab" >
        <div class="has-text-centered" id="info-container">
        <%= will_paginate @collection, renderer: BulmaPagination::Rails, class: "is-centered is-rounded" %>
          <div class="info-section">
            <% @informations.each do |information| %>
              <div class="card" id="info-card">
                <div class="card-image">
                  <% if information.image? %>
                    <%= image_tag information.image.url, id: :img_prev, class: "info-photo-size" %>
                  <% else %>
                    <%= image_tag "https://img-photo.s3-ap-northeast-1.amazonaws.com/uploads/content_image/info.jpg", id: :img_prev, class: "info-photo-size" %>
                  <% end %>
                </div>
                <div class="card-content">
                  <div class="content" id="info-content">
                    <p><%= l(information.created_at, format: :hyphen) %></p>
                    <p class="has-text-weight-bold">
                      <%= information.title %>
                    </p>
                    <%= information.news.truncate(30) %>
                  </div>
                </div>
                <footer class="card-footer">
                  <div class="card-footer-item">
                    <%= link_to edit_information_path(information) do %>
                      <button type="button" class="button is-success is-light is-medium"><i class="fas fa-edit"></i></button>
                    <% end %>
                  </div>
                  <div class="card-footer-item">
                    <%= link_to information_path(information), method: :delete,
                          data: { confirm: "#{information.title}のお知らせを削除してよろしいですか？" }, class:"button is-danger is-light is-medium" do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>
                </footer>
              </div>
            <% end %>
          </div>
        <%= will_paginate @collection, renderer: BulmaPagination::Rails, class: "is-centered is-rounded" %>
        </div>
      </div>

      <div id="Aud" class="content-tab" style="display:none">
        <div class="has-text-centered">
          <div class="panel-edit-container">
            <% @admin_informations.each do |information| %>
              <article class="panel" id="panel-edit-content">
                <div class="show-info-container">
                  <h1 class="show-info-title has-text-weight-bold is-size-5"><%= information.title %></h1>
                  <hr>
                  <div>
                    <span class="show-info-sp"><i class="fa fa-calendar-alt"></i><%= l( information.created_at, format: :dot) %></span><br>
                    <p class="show-info-p"><%=safe_join(information.news.split("\n"), tag.br) %></p>
                    <hr>

                    <div class="preview-contents">
                      <%= image_tag information.image.url, id: :img_prev, class: "info-photo-size" if information.image? %>
                      <% if information.url.present? %>
                        <iframe width="385" height="265" src="https://www.youtube.com/embed/<%= information.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                      <% end %>
                    </div>
                      <% if current_facility.admin? %>
                        <%= link_to edit_information_path(information) do %>
                          <button type="button" class="button is-success is-light is-medium"><i class="fas fa-edit"></i></button>
                        <% end %>
                      <% end %>
                  </div>
                </div>
              </article>
            <% end %>
          </div>
        </div>
      </div>
    </article>

    <%= render 'responsive_layout' %> <!--レスポンシブ対応のため記述-->

  </div>
</div>

<script>
  function openTab(evt, tabName) {
    var i, x, tablinks;
    x = document.getElementsByClassName("content-tab");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("panel-tab");
    for (i = 0; i < x.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" is-active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " is-active";
  }
</script>

<script>
  $(function(){
    ScrollReveal().reveal('.facility-icon-image', { delay: 600, distance: '70%', origin: 'top', duration: 2000, viewFactor: 0.5 });
    ScrollReveal().reveal('#facility-name', { delay: 100, distance: '100%', origin: 'left', duration: 2000, viewFactor: 0.5 });
  });
</script>

app/views/informations/new.html.erb
<%= render partial: 'shared/facility_images', locals: { facility: current_facility} %>

<div class="columns is-variable is-0 is-desktop facility-columns" style="margin-right: 0px; margin-top: -1.1rem;">
  <%= render 'shared/side_link' %>
  <div class="column is-10-desktop is-12-mobile" style="padding: 0px;">
    <nav class="panel" id="panel-style">
      <div class="notification-container" id="notification-mobile">
        <div class="content has-text-centered">
          <div class="columns is-centered">
            <div class="column is-10 top-btn-position is-centered">
              <h3 id="account-title">お知らせの新規投稿ができます。</h3>
              <small style="float: right">現在時刻 <%= l(Time.zone.now, format: :short) %></small>
              <h1 class="mini-title" style="font-size: 20px; color: #401c00;">お知らせ画像設定</h1>
              <p class="title-description">ここからお知らせに使用する背景画像の設定ができます。</p>
              <%= form_with(model: @information, url: informations_path, method: :post, local: true) do |f| %>
                <%= render partial: 'shared/error_messages', locals: { obj: @information } %>
                <div class="info-image-layout">
                  <%= @information.information_image %>
                </div>
                <div class="mobile-info-image-layout">
                  <%= @information.info_mobile_image %>
                  <div class="info-image-back">
                    <div class="info-image-camera">
                      <i class="fas fa-camera"></i>
                    </div>
                  </div>
                </div>
                <div class="drop-zone-area-info">
                  <%= f.label :image, "\uf574", class: "fa image_input_comment" %>
                  <%= f.file_field :image, value: "upload", class: "image_uploading" %>
                  <%= f.hidden_field :image_cache %>
                </div>
                <div class="position-control"><h1>位置調整</h1></div>
                <div class= "info-sub-title">
                  <p>お知らせタイトル</p>
                </div>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_field :title, :placeholder => "\uf303 タイトルを入力してください", class: "fa input" %>
                  </div>
                </div>
                <div class="info-sub2-title">
                  <p>本文</p>
                </div>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_area :news, :placeholder => "\uf303 お知らせを入力してください", class: "fa textarea" %>
                  </div>
                </div>
                <div class="info-sub2-title">
                  <p>YouTube動画</p>
                </div>
                <div class="media-content">
                  <div class="content label-space">
                    <%= f.text_field :url, :placeholder => "\uf303 動画URLを貼り付けてください", class: "fa input" %>
                  </div>
                </div>
                <%= f.submit "お知らせを新規投稿する", class: "info-btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= render 'responsive_layout' %> <!--レスポンシブ対応のため記述-->

  </div>
</div>

<script>
  $(function() {
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $(".image_uploading").change(function(){
        readURL(this);
    });
  });
</script>

<script>
  $(function() {
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#img_prev1').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $(".image_uploading").change(function(){
        readURL(this);
    });
  });
</script>

<script>
  $(function(){
    ScrollReveal().reveal('.facility-icon-image', { delay: 600, distance: '70%', origin: 'top', duration: 2000, viewFactor: 0.5 });
    ScrollReveal().reveal('#facility-name', { delay: 100, distance: '100%', origin: 'left', duration: 2000, viewFactor: 0.5 });
  });
</script>

app/views/informations/show.html.erb
<!--<div class="show-info-container">
  <hr>
  <h1 class="show-info-title"><%#= @information.title %></h1>
  <hr>
  <div>
    <span class="show-info-sp"><i class="fa fa-calendar-alt"></i> <%#= l( @information.created_at, format: :dot) %></span><br>
    <p class="show-info-p"><%#=safe_join(@information.news.split("\n"),tag(:br))%></p>
    <hr>
  </div>
  <%#= link_to top_notice_facility_informations_path(current_user), class:"button is-success is-outlined" do %>
    <i class="fas fa-arrow-left"></i>　戻る
  <%# end %>
</div>-->