config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'error_top', to: "static_pages#error_top"

  # メール機能 ============================================================================
  get '/request_mail/preview', to: 'request_mails#preview_mail'
  post '/request_mail/create', to: 'request_mails#send_mail'

  # 新規ユーザ作成（施設・ご家族） ========================================================
  resources :signup do
    collection do
      get 'step1'
      get 'step2' # ここで、入力が終了
      get 'step3'
      get 'search'
    end
  end

  # devise（施設・ご家族） ================================================================
  devise_for :facilities, controllers: {
      sessions: 'facilities/sessions',
      passwords: 'facilities/passwords',
      registrations: 'facilities/registrations'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :facility do
    get 'facility_sign_in', to: "facilities/sessions#new"
    get 'facility_sign_out', to: "facilities/sessions#destroy"
  end

  devise_scope :user do
    get 'sign_in', to: "users/sessions#new"
    get 'sign_out', to: "users/sessions#destroy"
    get 'privacy', to: "users/sessions#privacy"
  end

  # 施設 ==================================================================================
  resources :facilities do
    get :home # ユーザログイン後の各施設のホーム画面
    get :facility_home, on: :member # 施設ログイン後のホーム画面
    resources :reservations do # 予約機能
      collection do
        get :index_week
        get :index_past
      end
      get '/reservation_time/:date', on: :collection, to: 'reservations#reservation_time', as: :reservation_time
    end
    # get 'inquiry', to: "facilities/inquiries#inquiry"
    # post 'create', to: "facilities/inquiries#create"
    resources :inquiries do
      get :inquiry, on: :collection
    end
  end

  # ご家族 ================================================================================
  resources :users do
    member do
      get :video_room
    end
    resources :rooms, only: %i[new create edit update]
    resources :affiliations, only: %i[create destroy]
  end

  # カレンダー設定 =========================================================================
  resources :calendar_settings, except: :index

  # 利用施設登録 ==========================================================================
  resources :facility_users, only: %i[new update destroy] do
    member do
      patch :facility_update
    end
  end

  # 入居者 ================================================================================
  resources :residents do
    patch :leave_update, on: :member # 入退所
    resources :memories do # 思い出アルバム
      delete '/delete_image/:memory_id/:column', on: :collection, to: 'memories#delete_image', as: :delete_image
    end
  end

  # 入居者申請 ============================================================================
  resources :request_residents

  # 入居者登録 ============================================================================
  resources :relatives, except: %i[create] do
    get :confirm, on: :member
    patch :denial, on: :member
    patch :update_relatives, on: :collection
  end

  # お知らせ ==============================================================================
  resources :informations

  # タグ ==================================================================================
  resources :tags
  resources :tag_images

  # お問い合わせ ==========================================================================
  resources :inquiries do
    collection do
      get :inquiry
      get :inquiry_system
      post :create_system
    end
  end

  # 例外処理 ==============================================================================
  # get '*path', to: 'application#render_404'
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :resident

  validates :image0,  presence: true
  validates :title,   presence: true, length: { maximum: 20 }
  validates :message, presence: true
  validates :event_date, presence: true

  # モデル | ImageUploaderクラスとimageカラムを紐づける
  mount_uploader :image0, ImageUploader
  mount_uploader :image1, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader
  mount_uploader :image4, ImageUploader
  mount_uploader :image5, ImageUploader
  mount_uploader :image6, ImageUploader
  mount_uploader :image7, ImageUploader

  def delete_image(column)
    case column
    when "image1"
      remove_image1!
    when "image2"
      remove_image2!
    when "image3"
      remove_image3!
    when "image4"
      remove_image4!
    when "image5"
      remove_image5!
    when "image6"
      remove_image6!
    else
      remove_image7!
    end
  end

  def self.image_columns(memories)
    image_columns = []
    memories.each do |m|
      image_columns << m.image0 if m.image0?
      image_columns << m.image1 if m.image1?
      image_columns << m.image2 if m.image2?
      image_columns << m.image3 if m.image3?
      image_columns << m.image4 if m.image4?
      image_columns << m.image5 if m.image5?
      image_columns << m.image6 if m.image6?
      image_columns << m.image7 if m.image7?
    end
    image_columns
  end

  def self.total_image_count(residents, day)
    image_columns = []
    residents.each do |resident|
      resident.memories.where(created_at: day.all_month).find_each do |m|
        image_columns << m.image0 if m.image0?
        image_columns << m.image1 if m.image1?
        image_columns << m.image2 if m.image2?
        image_columns << m.image3 if m.image3?
        image_columns << m.image4 if m.image4?
        image_columns << m.image5 if m.image5?
        image_columns << m.image6 if m.image6?
        image_columns << m.image7 if m.image7?
      end
    end
    image_columns.count
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_resident
  before_action :set_memories, except: :destroy
  before_action :set_memory, only: %i[show edit update]
  before_action :add_images, only: %i[new edit]

  def index
    @image_columns = Memory.image_columns(@memories)
  end

  def show
    @residents = current_user.residents.includes(:memories) if user_signed_in?
  end

  def new
    @memory = @resident.memories.new
  end

  def create
    @memory = @resident.memories.new(memories_params)
    if @memory.save
      redirect_to resident_memory_url(@resident, @memory), notice: "#{@resident.name}さんの思い出アルバムを投稿しました。"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @memory.update(memories_params)
      redirect_to resident_memory_url, notice: "#{@resident.name}さんの思い出アルバムを編集しました。"
    else
      render :edit
    end
  end

  def destroy
    resident = current_facility.residents.find(params[:resident_id])
    memory = resident.memories.find(params[:id])
    memory.delete
    redirect_to resident_memories_url, alert: "#{resident.name}さんの思い出アルバムを削除しました"
  end

  def delete_image
    memory_id = params[:memory_id].to_i
    memory = @memories.find(memory_id)
    column = params[:column]
    memory.delete_image(column)
    memory.save
    if column != "image0"
      redirect_to resident_memories_url, alert: "画像を削除しました。"
    else
      redirect_to resident_memories_url, alert: "画像1は削除できません。"
    end
  end

  private

    def set_resident
      @resident = Resident.find(params[:resident_id])
    end

    def set_memories
      @memories = @resident.memories.order(updated_at: "DESC")
    end

    def set_memory
      @memory = @memories.find(params[:id])
    end

    def add_images
      @add_images = params[:add_images].to_i
    end

    def memories_params
      params.require(:memory).permit(:add_image, :title, :message, :event_date,
                                     :image0, :image1, :image2, :image3, :image4, :image5, :image6, :image7,
                                     :remove_image0, :remove_image1, :remove_image2, :remove_image3, :remove_image4, :remove_image5, :remove_image6, :remove_image7,
                                     :image0_cache, :image1_cache, :image2_cache, :image3_cache, :image4_cache, :image5_cache, :image6_cache, :image7_cache)
    end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/_all_images.html.erb
<% image_columns.each do |image| %>
  <% if Rails.env.production? %>
    <% memory_id = image.url.split("/")[6].to_i %>
    <% column = image.url.split("/")[5] %>
    <% id_column = image.url.split("/")[6] + image.url.split("/")[5] %>
    <% column_id = image.url.split("/")[5] + image.url.split("/")[6] %>
    <% url = image.url.split("/")[7] %>
    <% memory = memories.find(memory_id) %>
  <% else %>
    <% memory_id = image.url.split("/")[4].to_i %>
    <% column = image.url.split("/")[3] %>
    <% id_column = image.url.split("/")[4] + image.url.split("/")[3] %>
    <% column_id = image.url.split("/")[3] + image.url.split("/")[4] %>
    <% url = image.url.split("/")[5] %>
    <% memory = memories.find(memory_id) if facility_signed_in? %>
  <% end %>
  <%= image_tag image.url, class: "img-interval index-photo-size", id: id_column %>

  <!-- 画像モーダル表示 -->
  <div class="modal" id="<%= column_id %>">
    <div class="modal-background"></div>
    <div class="modal-card image-modal-width">
      <header class="modal-card-head" id="modal-title-back">
        <p class="modal-card-title is-half has-text-weight-bold reserve-modal title-color">画像データ詳細</p>
        <button class="delete" aria-label="close" id="close"></button>
      </header>

      <%= render partial: 'shared/error_messages', locals: { obj: memory } if facility_signed_in? %>
      <section class="modal-card-body image-position">
        <%= image_tag image.url, id: "img_prev_#{column}_#{memory_id}", class: "img-interval modal-photo-size" %>
        <%#= f.file_field :image0, class: "image_uploading_#{column}_#{memory_id} modal-input" %>
      </section>
      <section class="modal-card-body" id="content-back">
        <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">画像名</span><%= url %></p>
        <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">出来事の日付（行事日等）</span><%= l(image.model.event_date, format: :long) %></p>
        <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">思い出画像タイトル</span><%= image.model.title %></p>
        <p class="is-pulled-left word-break"><span class="has-text-weight-bold span-title">ご家族へのメッセージ</span><%= image.model.message %></p>
      </section>

      <footer class="modal-card-foot footer-position res-footer">
        <% if facility_signed_in? %>
          <%= form_with(model: memory, url: resident_memory_path(resident, memory), method: :patch, class: "img-update-form", local: true) do |f| %>
            <% case image.url.split("/")[3] %>
            <% when "image0" %>
              <%= f.hidden_field :image0_cache %> <!--変更なしの際のエラー解消-->
              <%= f.label :image0, "\uf093 画像を選択", class: "fa label" %> <!--sp→labelボタンを表示  pc→display: none;-->
              <%= f.file_field :image0, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %> <!--sp→display: none;  pc→file_fieldを表示-->
            <% when "image1" %>
              <%= f.hidden_field :image1_cache %>
              <%= f.label :image1, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image1, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% when "image2" %>
              <%= f.hidden_field :image2_cache %>
              <%= f.label :image2, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image2, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% when "image3" %>
              <%= f.hidden_field :image3_cache %>
              <%= f.label :image3, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image3, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% when "image4" %>
              <%= f.hidden_field :image4_cache %>
              <%= f.label :image4, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image4, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% when "image5" %>
              <%= f.hidden_field :image5_cache %>
              <%= f.label :image5, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image5, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% when "image6" %>
              <%= f.hidden_field :image6_cache %>
              <%= f.label :image6, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image6, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% else %>
              <%= f.hidden_field :image7_cache %>
              <%= f.label :image7, "\uf093 画像を選択", class: "fa label" %>
              <%= f.file_field :image7, class: "image_uploading_#{column}_#{memory_id} d-none drop-zone" %>
            <% end %>
            <%= f.submit "\uf302 変更する", class: "fa button img-update-btn" %>

            <%= link_to delete_image_resident_memories_path(resident, memory_id: memory_id, column: column),
                        method: :delete, data: { confirm: "トップ画像(#{url})は削除できません。"}, class: "button is-medium delete-btn" do %>
              <span><i class="far fa-trash-alt"></i></span>
            <% end %>
          <% end %>
        <% else %>
          <!--登録先フォルダを選択して、画像を登録する （tag_image/create ⇨ create.js.erb ⇨ viewに表示）-->
          <%= form_with(model: current_user, url: tag_images_path(image: url), method: :post, class: "tag-select-form", remote: true) do |f| %>
            <div class="cp_ipselect cp_sl04">
              <%= f.collection_select :tag_id, current_user.tags, :id, :title, { prompt: '追加したいフォルダを選択' }, {class: "select-tag"} %>
              <%= f.hidden_field :image, :value => url %>
            </div>
            <%= f.submit "\uf302 追加する", class: "fa tag-select-submit" %>
          <% end %>
        <% end %>
      </footer>
    </div>
  </div>

  <script>
    $(document).ready(function () {
      $("#<%= id_column %>").on("click", function () {
        $("div#<%= column_id %>").addClass("is-active");
      })
      $("#close, div.modal-background").on("click", function () {
        $("div#<%= column_id %>").removeClass("is-active");
      })
    });

    $(function() {
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#img_prev_<%= column %>_<%= memory_id %>").attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
        }
      }
      $(".image_uploading_<%= column %>_<%= memory_id %>").change(function(){
        readURL(this);
      });
    });
  </script>
<% end %>

<%# <div class="bottom-control">&nbsp;</div> %>

app/views/memories/_clock.html.erb
<script>
  Vue.component('clock', {
    data: function() {
      return {
        time: '12:34:56'
      }
    },
    mounted: function() {
      let timerID = setInterval(this.refresh ,500);
    },
    methods: {
      refresh: function () {
        let now = new Date();
        if (now.getHours() > 10 && now.getMinutes() > 10) {
          this.time = `${now.getHours()}:${now.getMinutes()}`;
        } else if (now.getHours() < 10 && now.getMinutes() > 10) {
          this.time = `0${now.getHours()}:${now.getMinutes()}`;
        } else if (now.getHours() > 10 && now.getMinutes() < 10) {
          this.time = `${now.getHours()}:0${now.getMinutes()}`;
        } else {
          this.time = `0${now.getHours()}:0${now.getMinutes()}`;
        }
      }
    },
    template: '<span>{{ time }}</span>'
  });
  var app = new Vue({
    el: "#app"
  });
</script>

app/views/memories/_event_card.html.erb
<div id="event-card-show">
  <% if user_signed_in? %>
    <% residents.each do |resident| %>
      <% resident.memories.each do |m| %>
        <div class="card-float card-inline-block" id="card-point">
          <section class="photo-card card-inline-block">
            <%= image_tag m.image0.url, class: "card-photo-size" if m.image0.present? %>
            <div class="photo-card-content">
              <p class="photo-card-title"><%= m.title %></p>
              <p class="photo-card-text"><%= m.message.truncate(20) %></p>
            </div>
            <div class="photo-card-link">
              <%= link_to resident_memory_path(resident, m), class:"folder", remote: true do %>
                <i class="fas fa-folder-open fa-3x"></i>
              <% end %>

              <p class="photo-card-text">行事日: <%= l(m.event_date, format: :long) %></p>
            </div>
          </section>
        </div>
      <% end %>
    <% end %>

  <% else %>
    <% resident.memories.each do |m| %>
      <div class="card-float card-inline-block">
        <section class="photo-card card-inline-block">
          <%= image_tag m.image0.url, class: "card-photo-size" if m.image0.present? %>
          <div class="photo-card-content">
            <p class="photo-card-title"><%= m.title %></p>
            <p class="photo-card-text"><%= m.message.truncate(20) %></p>
          </div>
          <div class="photo-card-link">
            <%= link_to resident_memory_path(resident, m), class:"folder", remote: true do %>
              <i class="fas fa-folder-open fa-3x"></i>
            <% end %>

            <% if facility_signed_in? %>
              <%= link_to new_resident_memory_path(resident, add_images: m), class: "folder" do %>
                <i class="fas fa-folder-plus fa-3x"></i>
              <% end %>
            <% end %>
            <p class="photo-card-text">行事日: <%= l(m.event_date, format: :long) %></p>
          </div>
        </section>
      </div>
    <% end %>
  <% end %>
</div>

app/views/memories/_show.html.erb
<div id="back-to-event-card">
  <section class="hero is-medium has-text-centered" id="hero-memory">
    <div class="main-show">
      <div class="content">
        <!--画像部分-->
        <%= image_tag @memory.image0.url, class: "img-interval show-photo-size" if @memory.image0? %>
        <%= image_tag @memory.image1.url, class: "img-interval show-photo-size" if @memory.image1? %>
        <%= image_tag @memory.image2.url, class: "img-interval show-photo-size" if @memory.image2? %>
        <%= image_tag @memory.image3.url, class: "img-interval show-photo-size" if @memory.image3? %>
        <%= image_tag @memory.image4.url, class: "img-interval show-photo-size" if @memory.image4? %>
        <%= image_tag @memory.image5.url, class: "img-interval show-photo-size" if @memory.image5? %>
        <%= image_tag @memory.image6.url, class: "img-interval show-photo-size" if @memory.image6? %>
        <%= image_tag @memory.image7.url, class: "img-interval show-photo-size" if @memory.image7? %>

        <!--タイトル/メッセージ部分-->
        <div class="photo-card-link-show">
          <h4 class="title-brown"><%= @memory.title %></h4>
          <p class="message-title"><%= @memory.message %></p>
          <p class="photo-card-text-show">行事日: <%= l(@memory.event_date, format: :long) %>（最終投稿日: <%= l(@memory.updated_at, format: :long) %>）</p>
          <% if facility_signed_in? %>
            <%= link_to edit_resident_memory_path(@resident, @memory) do %>
              <button type="button" class="button is-success is-light is-medium edit-btn"><i class="fas fa-edit"></i></button>
            <% end %>
            <%= link_to resident_memory_path(@resident, @memory), method: :delete,
                        data: { confirm: "削除してよろしいですか？" }, class:"button is-danger is-light is-medium delete-btn" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
            <%= link_to new_resident_memory_path(@resident, add_images: @memory), class: "folder" do %>
              <i class="fas fa-folder-plus fa-3x"></i>
            <% end %>
          <% end %>

            <div class="memories-index-btn">
              <button id="back-to-event-card-btn" class="button is-link is-light is-medium index-btn"><i class="fas fa-images"></i>&nbsp;行事ごとの写真一覧へ戻る</button>
            </div>
        </div>
      </div>

      <% if facility_signed_in? %>
        <!--追加画像カードへのリンク画像-->
        <div class="otherNavigation">
          <h1>下記の画像をクリックすると、該当する画像ページへ移動できます。</h1>
        </div>
        <div class="content">
          <% @memories.each do |m| %>
            <% if @memory.event_date == m.event_date && @memory.id != m.id %>
              <%= link_to resident_memory_path(@resident, m), class:"folder", remote: true do %>
                <%= image_tag m.image0.url, class: "img-interval show-photo-size" if m.image0? %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <!--同じ行事タイトルの画像一覧を表示させる-->
      <div class="otherNavigation">
        <h1>行事日【<%= l(@memory.event_date, format: :long) %>】と同じ画像を表示</h1>
      </div>
      <div class="content show-bottom-control">
        <% @memories.map do |m| %>
          <% if m.event_date == @memory.event_date %>
            <% if @memory.id != m.id %>
              <%= image_tag m.image0.url, class: "img-interval show-photo-size" if m.image0? %>
              <%= image_tag m.image1.url, class: "img-interval show-photo-size" if m.image1? %>
              <%= image_tag m.image2.url, class: "img-interval show-photo-size" if m.image2? %>
              <%= image_tag m.image3.url, class: "img-interval show-photo-size" if m.image3? %>
              <%= image_tag m.image4.url, class: "img-interval show-photo-size" if m.image4? %>
              <%= image_tag m.image5.url, class: "img-interval show-photo-size" if m.image5? %>
              <%= image_tag m.image6.url, class: "img-interval show-photo-size" if m.image6? %>
              <%= image_tag m.image7.url, class: "img-interval show-photo-size" if m.image7? %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>

<% if user_signed_in? %>
  <script>
    $(function() {
      $('#back-to-event-card-btn').click(function() {
        $('#back-to-event-card').html("<%= escape_javascript(render 'event_card', { residents: @residents }) %>").hide().fadeIn();
      });
    });
  </script>
<% else %>
  <script>
    $(function() {
      $('#back-to-event-card-btn').click(function() {
        $('#back-to-event-card').html("<%= escape_javascript(render 'event_card', { resident: @resident }) %>").hide().fadeIn();
      });
    });
  </script>
<% end %>

app/views/memories/edit.html.erb
<nav class="panel" id="memory-panel-style">
  <div class="notification-container notice-pad">
    <div class="content has-text-centered">
      <div class="columns is-centered">
        <div class="column is-12 is-centered max-width">
          <h1 class="memory-title">思い出アルバムの編集ができます。</h1>
          <small class="is-pulled-right">
            現在時刻&nbsp;<span id="app"><%= l(Date.current) %>&nbsp;<clock></clock></span>
          </small>
          <h1 class="memory-title-mini">思い出アルバムの画像選定/編集</h1>
          <p class="has-text-left">ここから思い出アルバムに使用する画像を最大８枚まで選定/編集できます。</p>
          <%= render 'edit-card' %>
        </div>
      </div>
    </div>
  </div>
</nav>
<%= render 'clock' %>

app/views/memories/index.html.erb
<section class="hero is-medium has-text-centered" id="hero-memory">
  <div class="glovalNavigation">
    <h1 class="has-text-weight-bold"><%= @resident.name %>さんの思い出アルバム</h1>
  </div>

  <div class="main-index">
    <div id="insert-photo">
      <%= link_to new_resident_memory_path(@resident), class: "button is-link is-pulled-right" do %>
        <i class="fas fa-images has-text-weight-bold">&ensp;新しい写真を投稿</i>
      <% end %>
    </div>
    <div class="content">
      <div class="cp_tab">
        <input type="radio" name="cp_tab" id="tab1_1" aria-controls="first_tab01" checked>
        <label for="tab1_1" class="tab-font">全ての写真</label>
        <input type="radio" name="cp_tab" id="tab1_2" aria-controls="second_tab01">
        <label for="tab1_2" class="tab-font">行事ごとの写真</label>

        <div class="cp_tabpanels">

          <!--全ての写真のタブ-->
          <div id="first_tab01" class="cp_tabpanel all-render">
            <%= render 'all_images', { image_columns: @image_columns, memories: @memories, resident: @resident } %>
          </div>

          <!--行事ごとの写真(カード)のタブ-->
          <div id="second_tab01" class="cp_tabpanel event-render">
            <%= render 'event_card', { resident: @resident } %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/memories/show.html.erb
<section class="hero is-medium has-text-centered" id="hero-memory">
  <div class="glovalNavigation">
    <h1 class="has-text-weight-bold"><%= @resident.name %>さんの思い出アルバム</h1>
  </div>

  <div class="main-show">
    <div class="content">
      <!--画像部分-->
      <%= image_tag @memory.image0.url, class: "img-interval show-photo-size" if @memory.image0? %>
      <%= image_tag @memory.image1.url, class: "img-interval show-photo-size" if @memory.image1? %>
      <%= image_tag @memory.image2.url, class: "img-interval show-photo-size" if @memory.image2? %>
      <%= image_tag @memory.image3.url, class: "img-interval show-photo-size" if @memory.image3? %>
      <%= image_tag @memory.image4.url, class: "img-interval show-photo-size" if @memory.image4? %>
      <%= image_tag @memory.image5.url, class: "img-interval show-photo-size" if @memory.image5? %>
      <%= image_tag @memory.image6.url, class: "img-interval show-photo-size" if @memory.image6? %>
      <%= image_tag @memory.image7.url, class: "img-interval show-photo-size" if @memory.image7? %>

      <!--タイトル/メッセージ部分-->
      <div class="photo-card-link-show">
        <h4 class="title-brown"><%= @memory.title %></h4>
        <p class="message-title"><%= @memory.message %></p>
        <p class="photo-card-text-show">行事日: <%= l(@memory.event_date, format: :long) %>（最終投稿日: <%= l(@memory.updated_at, format: :long) %>）</p>
        <% if facility_signed_in? %>
          <%= link_to edit_resident_memory_path(@resident, @memory) do %>
            <button type="button" class="button is-success is-light is-medium edit-btn"><i class="fas fa-edit"></i></button>
          <% end %>
          <%= link_to resident_memory_path(@resident, @memory), method: :delete,
                      data: { confirm: "削除してよろしいですか？" }, class:"button is-danger is-light is-medium delete-btn" do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
          <%= link_to new_resident_memory_path(@resident, add_images: @memory), class: "folder" do %>
            <i class="fas fa-folder-plus fa-3x"></i>
          <% end %>

          <div class="memories-index-btn">
            <%= link_to resident_memories_path(@resident), class:"button is-link is-light is-medium index-btn" do %>
              <i class="fas fa-images"></i>&nbsp;思い出アルバムへ戻る
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <!--追加画像カードへのリンク画像-->
    <div class="otherNavigation">
      <h1>下記の画像をクリックすると、該当する画像ページへ移動できます。</h1>
    </div>
    <div class="content">
      <% @memories.each do |m| %>
        <% if @memory.event_date == m.event_date && @memory.id != m.id %>
          <%= link_to resident_memory_path(@resident, m), class:"folder" do %>
            <%= image_tag m.image0.url, class: "img-interval show-photo-size" if m.image0? %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <!--同じ行事タイトルの画像一覧を表示させる-->
    <div class="otherNavigation">
      <h1>行事日【<%= l(@memory.event_date, format: :long) %>】と同じ画像を表示</h1>
    </div>
    <div class="content show-bottom-control">
      <% @memories.map do |m| %>
        <% if m.event_date == @memory.event_date %>
          <% if @memory.id != m.id %>
            <%= image_tag m.image0.url, class: "img-interval show-photo-size" if m.image0? %>
            <%= image_tag m.image1.url, class: "img-interval show-photo-size" if m.image1? %>
            <%= image_tag m.image2.url, class: "img-interval show-photo-size" if m.image2? %>
            <%= image_tag m.image3.url, class: "img-interval show-photo-size" if m.image3? %>
            <%= image_tag m.image4.url, class: "img-interval show-photo-size" if m.image4? %>
            <%= image_tag m.image5.url, class: "img-interval show-photo-size" if m.image5? %>
            <%= image_tag m.image6.url, class: "img-interval show-photo-size" if m.image6? %>
            <%= image_tag m.image7.url, class: "img-interval show-photo-size" if m.image7? %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>